version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    image: postgres
    environment:
      POSTGRES_DB: CatalogDb
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

volumes:
  postgres_catalog:
